graph TD
A[fa:fa-table Raw gene expression] --> B>read_mtx]
B --> C[fa:fa-table GE symbol + n cells]
C --> D>qc_cells]
D --> E[fa:fa-table QC data.frame]
E --> E1>plot_qc_cells]
E1 --> E2[fa:fa-chart-bar QC graphs]
E --> E3>define_cycling_cells]
E3 --> E4[fa:fa-chart-bar Cell cycle graphs]
E3 --> E5[fa:fa-table Non-cycling cells]
C --> F>qc_filter]
E --> F>qc_filter]
F --> G[fa:fa-table GE symbol + n' cells]
G --> H>convert_to_coord]
H --> I[fa:fa-table GE coord + n' cells]
I --> J>norm_ge]
J --> JJ[fa:fa-table Normalized GE]
JJ --> K>bin_genes]
K --> KK[fa:fa-table Norm. bin expression]
KK --> L>zscore]
L --> LL[fa:fa-table Norm. bin Z-score]
LL --> M>smooth_movingw]
M --> MM[fa:fa-table Norm. smoothed bin Z-score]
MM --> N>run_pca]
E5 -.-> N
N --> NN[fa:fa-table PCA results]
NN --> O>find_communities]
O --> OO[fa:fa-table Cell + community data.frame]
OO --> O2>plot_communities]
O2 --> O3[fa:fa-chart-bar Community graphs]
E -.-> O2
NN --> P>run_tsne]
P --> PP[fa:fa-table Cell + tSNE data.frame]
PP --> P2>plot_tsne]
P2 --> P3[fa:fa-chart-bar tSNE graphs]
E -.-> P2
OO -.-> P2

classDef orange fill:#f96;
class B,D,E1,E3,F,H,J,K,L,M,N,O,O2,P,P2 orange
