# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the normalization factor
#' 
#' @param ge gene expression amtrix
#' @param cont index of the control sample. R index so starting at 1.
#' @export
tmmNormC <- function(ge, cont) {
    .Call('_scCNAutils_tmmNormC', PACKAGE = 'scCNAutils', ge, cont)
}

