# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bin genes
#' 
#' @param ge an ordered gene expression matrix
#' @param bins a vector with bin ids
binGenesC <- function(ge, bins) {
    .Call('_scCNAutils_binGenesC', PACKAGE = 'scCNAutils', ge, bins)
}

#' Smooth signal
#' 
#' @param ge an ordered gene expression matrix
#' @param winsize the size of the sliding window (assumed to be odd).
smoothMovingC <- function(ge, winsize) {
    .Call('_scCNAutils_smoothMovingC', PACKAGE = 'scCNAutils', ge, winsize)
}

#' Compute the normalization factor
#' 
#' @param ge gene expression amtrix
#' @param cont index of the control sample. R index so starting at 1.
tmmNormC <- function(ge, cont) {
    .Call('_scCNAutils_tmmNormC', PACKAGE = 'scCNAutils', ge, cont)
}

